// Mocks generated by Mockito 5.0.16 from annotations
// in flutter_movies_app/test/get_movies_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:flutter_movies_app/src/domain/entities/movie.dart' as _i4;
import 'package:flutter_movies_app/src/domain/repositories/movie_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i2.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Movie>> getTrending({int? page, String? language}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getTrending, [], {#page: page, #language: language}),
              returnValue: Future<List<_i4.Movie>>.value(<_i4.Movie>[]))
          as _i3.Future<List<_i4.Movie>>);
  @override
  String toString() => super.toString();
}
